webtalk_init -webtalk_dir C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.sim/sim_1/behav/xsim/xsim.dir/top_module_jpeg_compression_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb 20 11:39:42 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "834b6d97-8a03-42d3-b974-830f20a10052" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71b4fbf45e8d4cd8a900d9cc442352b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8600_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1484169961 -regid "" -xml C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.sim/sim_1/behav/xsim/xsim.dir/top_module_jpeg_compression_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.sim/sim_1/behav/xsim/xsim.dir/top_module_jpeg_compression_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.sim/sim_1/behav/xsim/xsim.dir/top_module_jpeg_compression_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
