# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/hp/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6804-DESKTOP-I7K0TLI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.cache/wt [current_project]
set_property parent.project_path C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_image_compression.srcs/sources_1/imports/jpeg_image_compression/cosine_pck.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/dct_transform.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/dct_transform_streaming.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/jpeg_type_pkg.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/simple_dual_ram.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/memory_controller.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/quant_block_buf.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/quantization.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/rgb_to_ycbcr_converter.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/zigzag_encoding.vhd
  C:/Users/hp/Documents/FGPA/mini_project/jpeg_image_compression/top_level.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
